#!/bin/bash

# ttools: tools for linux based software project development 
# Copyright (c) 2021 Artur Bak. All Rights Reserved.
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

source env/src.env
source env/target.env

if [ "$MODE" == "dev" ]; then
    echo "DEV mode"
    DEV_POSTFIX=""
else
    echo "PROD mode"
    DEV_POSTFIX="--no-dev"
fi

function DBG {
    echo "$1:$2"
}

function WARN {
    echo "[WARN]$1:$2"
}

function ERR {
    echo "[ERR]$1:$2"
}

function removeExistingDir {

    if [ -z "$1" ]; then
        DBG "tbase:removeExistingDir" "ERR: empty param may cause system corruption. Exit."
        exit
    fi

    if [ -d $1 ]; then
        DBG "tremoveExistingDir" " $1"
        rm -Rf $1/
    fi
}

# Creates clean directory even if it already exists (old one is deleted) 
function createCleanDir {
    
    removeExistingDir $1

    DBG "createCleanDir" "create $1"
    mkdir -p $1
}

function parseParams {

    COMMAND=$1
    for p in "${@:2}"
    do
        #if [ -z "${p##[0-9]*}" ]; then

        if [ "${p:0:5}" == "-url=" ]; then
            BASE_URL=${p:5}
            echo "BASE_URL set to '$BASE_URL'"
        elif [ "${p:0:5}" == "-src=" ]; then
            SRC_DIR=${p:5}
            echo "SRC_DIR set to '$SRC_DIR'"
        elif [ "${p:0:5}" == "-out=" ]; then
            TARGET_DIR=${p:5}
            echo "TARGET_DIR set to '$TARGET_DIR'"
        elif [ "$p" == "-docker" ]; then
            echo "DOCKERIZE set to 'yes'"
            DOCKERIZE=yes
        #else
        #    echo Unknown param: $p
        fi
    done
}
